<!-- Creates the bootstrap modal where the image will appear -->
<div class="modal fade modal-resize modal-primary" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel"><?php echo $this->translate('Visualizar Imagem'); ?></h4>
            </div>
            <div class="modal-body">
                <img src="" id="imagepreview" style="max-width: 760px; max-height: 564px;" >
            </div>
            <div class="modal-footer">
                <!-- Logo -->
                <div class="pull-left">
                    <img class="modal-footer-logo">
                </div>
                <!-- Fim logo -->

                <div class="clearfix"></div>

                <div class="pull-right">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Fechar'); ?></button>
                </div>

            </div>
        </div>
    </div>
</div>