<?php

$this->headScript()->prependFile($this->basePath() . '/js/app/cliente.js?' . VERSAO_ATUALIZACAO);

$this->headTitle($this->conf['titulo']);

$form = $this->form;
$fieldset = $form->get('filtro');

$form->prepare();

/** @var \Zend\Paginator\Paginator $clientes */
$clientes = $this->clientes;

?>
<div class="bs-callout bs-callout-info">
    <h4><?php echo $this->escapeHtml($this->conf['titulo']); ?></h4>

    <p><?php echo $this->escapeHtml($this->conf['texto']); ?></p>
</div>

<div class="mensagens-alerta">
    <div class="row">
        <?= $this->alertMessage() ?>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-xs-5 col-sm-6 col-md-6 col-lg-6 pull-left text-left">
                Filtro de Pesquisa
            </div>
            <div class="col-xs-5 col-sm-6 col-md-6 col-lg-6 pull-right text-right">
                <a class="btn btn-primary" href="<?php echo $this->url('cliente', array('action' => 'editar')); ?>"><i
                        class="glyphicon glyphicon-plus"></i> Novo Cliente</a>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <?= $this->form()->openTag($form); ?>

        <div class="row">
            <?php echo $this->partial('partials/form-group', ['fieldset' => $fieldset->get('nome'), 'divClass' => 'col-xs-12 col-sm-12 col-md-4 col-lg-4']); ?>
            <?php echo $this->partial('partials/form-group', ['fieldset' => $fieldset->get('email'), 'divClass' => 'col-xs-12 col-sm-12 col-md-4 col-lg-4']); ?>
            <?php echo $this->partial('partials/form-group', ['fieldset' => $fieldset->get('ativo'), 'divClass' => 'col-xs-12 col-sm-12 col-md-4 col-lg-4']); ?>
        </div>

        <div class="row">
            <?php echo $this->partial('partials/form-group', ['fieldset' => $fieldset->get('regiao'), 'divClass' => 'col-xs-12 col-sm-12 col-md-4 col-lg-4']); ?>
        </div>

        <div class="row pull-right">
            <div class="col-xs-5 col-sm-6 col-md-6 col-lg-6 text-left">
                <button class="btn btn-default" type="submit">
                    <i class="glyphicon glyphicon-filter"></i> Pesquisar!
                </button>
            </div>
        </div>
        <?= $this->form()->closeTag() ?>
    </div>
</div>

<?php $msgs = $this->flashMessenger()->getMessages();
foreach ($msgs as $msg) : ?>
    <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span
                class="sr-only">Fechar</span></button>
        <i class="glyphicon glyphicon-exclamation-sign text-warning"></i> <strong><?php echo $msg; ?></strong>
    </div>
<?php endforeach; ?>

<?php if (null == $clientes) : ?>

    <div class="row text-center">
        <h2 class="text-center">Informe um filtro para pesquisa.</h2>
    </div>

<?php else: ?>

    <div class="row">
        <section class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <table data-ordenado="3" data-direcao="desc" class="data-table table table-striped table-bordered nowrap">
                <thead>
                <tr>
                    <th>Nome</th>
                    <th>E-mail</th>
                    <th>Telefone</th>
                    <th>Região</th>
                    <th class="hidden-xs date-column">Cadastrado Em</th>
                    <th class="hidden-xs">Status</th>
                    <th>Ações</th>
                </tr>
                </thead>
                <tbody>

                <?php
                /** @var \Application\Entity\Cliente $cliente */
                foreach ($clientes as $cliente) : ?>

                    <?php
                    $fotoPath = BASE_PATH . DS . 'public_html' . DS . 'images' . DS . 'sem-foto.png';
                    if ($cliente->possuiFoto()) {
                        $fotoPath = BASE_PATH . $cliente->getFoto();
                    }
                    $urlFoto = $this->url(
                        'imagem-mini',
                        [
                            'path' => base64_encode($fotoPath),
                        ]
                    );

                    ?>
                    <tr>
                        <td class="valign-middle"><span style="padding-right: 15px;"><img
                                    src="<?php echo $urlFoto; ?>"/></span><?php echo $this->escapeHtml($cliente->getNome()); ?>
                        </td>
                        <td class="valign-middle"><?php echo $this->escapeHtml($cliente->getEmail()); ?></td>
                        <td class="valign-middle"><?php echo $this->escapeHtml($cliente->getTelefone()); ?></td>
                        <td class="valign-middle hidden-xs"><?php echo ($cliente->getRegiao()) ? $this->escapeHtml($cliente->getRegiao()->getNome()) : ''; ?></td>
                        <td class="valign-middle hidden-xs"><?php echo $this->getDateOrUninformedToCurrentLocale($cliente->getDataCriacao()); ?></td>
                        <td class="valign-middle hidden-xs"><?php if ($cliente->isAtivo()) {
                                echo '<i class="glyphicon glyphicon-ok text-success"></i>';
                            } else {
                                echo '<i class="glyphicon glyphicon-remove text-danger"></i>';
                            } ?></td>
                        <td class='valign-middle text-center'><a href="<?php echo $this->url(
                                'cliente',
                                array(
                                    'action' => 'editar',
                                    'identificador' => $cliente->getId(),
                                )
                            ); ?>" class="btn btn-success btn-xs">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Editar</a>
                            <a href="<?php echo $this->url(
                                'cliente',
                                array(
                                    'action' => 'excluir',
                                    'identificador' => $cliente->getId(),
                                )
                            ); ?>" title="Deseja  Excluir <?php echo $cliente->getNome(); ?>"
                               class="btn-excluir-cliente btn btn-danger btn-xs">
                                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Excluir</a></td>
                    </tr>
                <?php endforeach;
                if (count($clientes) == 0) {
                    ?>
                    <tr>
                        <td colspan="6"><h2 class="text-center">Nenhum resultado encontrado!</h2></td>
                    </tr>
                <?php } ?>

                </tbody>
            </table>

        </section>
    </div>

<?php endif; ?>



<!-- Modal para confirmar a ação do usuário -->
<div class="modal fade modal-primary" id="confirm-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-loading-title" id="myModalLabel"><?php echo $this->translate('Essentia - Teste Marcelo'); ?></h4>
            </div>

            <div class="modal-body" id="modal-body-confirm">
                <?php echo $this->translate("Deseja realmente executar a ação neste registro?");?>
            </div>
            <div class="modal-footer">
                <button type='button' class='btn btn-success btn-sim'><?php echo $this->translate('Sim'); ?></button>
                <button type='button' class='btn btn-danger btn-nao'><?php echo $this->translate('Não'); ?></button>
            </div>
        </div>
    </div>
</div>
<!-- Modal para confirmar a ação do usuário -->