<!-- Modal de loading -->
<div class="modal fade modal-primary" id="modal-loading" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Header -->
            <div class="modal-header">
                <h4 class="modal-loading-title" id="myModalLabel"><?php echo $this->translate('AQUAERIS - Engenharia e Soluções Ambientais');?></h4>
            </div>
            <!-- Fim header -->

            <!-- Body -->
            <div class="modal-body">
                <div id="wrapper-loading">
                    <div id="modal-loading-mensagem"><p class="pull-left content"><?php echo $this->translate('Por favor, aguarde...');?></p></div>
                    <img src="/images/loaders/loader31.gif" alt="Carregando" class="pull-right" style="margin: 2px 0 0 10px"/>
                </div>
            </div>
            <!-- Fim body -->

            <!-- Footer -->
            <div class="modal-footer">

                <!-- Logo -->
                <div class="pull-left">
                    <img class="modal-footer-logo">
                </div>
                <!-- Fim logo -->

                <div class="clearfix"></div>
            </div>
            <!-- Fim footer -->
        </div>
    </div>
</div>
<!-- Fim modal de loading -->