<div id="topo">
    <div class="container">

        <a href="<?= $this->url('home'); ?>">
            <img src="/images/logos/intelbras-white.png" style="margin-top: 7px; margin-left: 16px" class="pull-left" />
        </a>

        <ul class="pull-right wrapper-topo-menu">
            <li>
                <a class="btn-usuario" href="#" style="cursor: default;">
                    <img src="<?php echo $this->basePath() . "/images/icons/user.jpg" ?>">
                    <span class="font-topo"> Visitante </span>
                </a>
            </li>
        </ul>

    </div>
</div>
